# Generated by Django 6.0.1 on 2026-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_embeddable',
            field=models.BooleanField(default=True, help_text='False = YouTube blocked embedding. Hidden from all listings.'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_embeddable'], name='sonyApp_vid_is_embe_b1ec44_idx'),
        ),
    ]
