# Generated by Django 6.0.1 on 2026-02-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyApp', '0002_video_is_embeddable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='last_updated',
            field=models.DateField(blank=True, help_text='Last date when view count was updated', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count_history',
            field=models.JSONField(default=dict, help_text='Daily snapshot of view counts: {"YYYY-MM-DD": count}'),
        ),
    ]
