# Generated by Django 6.0.1 on 2026-03-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonyApp', '0003_video_last_updated_video_view_count_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='video',
            name='base_snapshot_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the very first snapshot taken after publish. Used to determine section eligibility.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='last_snapshot_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent snapshot stored.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count_history',
            field=models.JSONField(default=dict, help_text='6h snapshots: {"YYYY-MM-DD HH:00": view_count}'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['base_snapshot_timestamp'], name='sonyApp_vid_base_sn_03b72d_idx'),
        ),
    ]
